### ISSUE TITLE
[Init] google icons 세팅

### ISSUE THREAD

**Issue by gudusol** [NOWSOPT-CDSP-WEB-1/Brunch-Web-Client#16]
## 🛠 Issue

- google icons 를 사용할 수 있도록 프로젝트 세팅 추가

## 📝 To-do

- [ ] google icon meta 태그 추가
- [ ] icon 파일 추가
- [ ] Icon 공용 컴포넌트 추가
