### ISSUE TITLE
[Feat] 작가 신청 페이지 퍼블리싱

### ISSUE THREAD

**Issue by pepperdad** [NOWSOPT-CDSP-WEB-1/Brunch-Web-Client#25]
## 🛠 Issue

- 작가 신청 페이지 UI 추가

## 📝 To-do

- [x] 자격 조건 섹션
- [x] 필수 자료 섹션
- [x] 유의 사항 섹션
- [x] 헤더
- [x] 푸터
