### ISSUE TITLE
[Feat] library 페이지 - 최근본책 구현

### ISSUE THREAD

**Issue by Bowoon1216** [NOWSOPT-CDSP-WEB-1/Brunch-Web-Client#43]
## 🛠 Issue

- 라이브러리 페이지의 최근 본 브런치북 파트를 구현합니다

## 📝 To-do

- [ ] 왼쪽 포커스된 책 컴포넌트 이용해서 구현
- [ ] 오른쪽 대기 중인(?) 책들 구현하고 
- [ ] 옮기는 버튼 구현
