### ISSUE TITLE
[Feat] 메인페이지 보수공사

### ISSUE THREAD

**Issue by gudusol** [NOWSOPT-CDSP-WEB-1/Brunch-Web-Client#46]
## 🛠 Issue

- 메인페이지 보수공사

## 📝 To-do

- [ ] 메인페이지 스타일 깨지는 부분 수정
- [ ] 메인페이지 피그마랑 다른 부분 수정
- [ ] 메인페이지 코드 리팩토링
- [ ] 화이팅!

**Comment by pepperdad** [comment]
파이팅!
